name: Ruff django Lint Check
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Ruff Linting
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select DJ,F,E,W,I,B,S --ignore E501,I001,W293,W291,W292
          pass-with-no-files: true